os: linux
branches:
  only:
    - master
language: node_js
node_js:
  - 14

git:
  depth: 3
  quiet: true
  submodules: false

cache:
  directories:
    - .yarn/cache
    - node_modules

script: bash ./scripts/ci-build.sh

deploy:
  provider: pages
  local-dir: ./dist
  target-branch: build
  email: tksudharshan@gmail.com
  name: tks18
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
